package main

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
)

// envHome overrides the state directory. Useful for testing and for anyone who
// keeps dotfiles somewhere other than the home directory.
const envHome = envPrefix + "HOME"

// resolveStateDir returns the directory holding config.json, projects.json,
// sessions.json and the session logs.
func resolveStateDir() (string, error) {
	if dir := os.Getenv(envHome); dir != "" {
		return dir, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("determine home directory (set %s to override): %w", envHome, err)
	}
	return filepath.Join(home, "."+appName), nil
}

// envClaudeBin points at the claude executable. Prefixed rather than a bare
// CLAUDE_BIN, which is a name other tooling could plausibly claim.
const envClaudeBin = envPrefix + "CLAUDE_BIN"

func resolveClaudeBin() string {
	if bin := os.Getenv(envClaudeBin); bin != "" {
		return bin
	}
	return "claude"
}

// logFileFor names the log for a project's environment.
//
// The base name makes it recognisable and the path digest makes it unique:
// two projects called "api" in different directories are different
// environments and must not write to the same file.
func logFileFor(home, projectPath string) string {
	digest := sha256.Sum256([]byte(projectPath))
	name := fmt.Sprintf("%s-%x.log", sanitizeSegment(filepath.Base(projectPath)), digest[:4])
	return filepath.Join(logsDir(home), name)
}

// Layout of the state directory:
//
//	config.json               yours — edited by hand or through `config`
//	state/projects.json       derived from a scan, replaced wholesale by rescan
//	state/environments.json   the record of running processes
//	state/logs/               output of those processes
//
// The split says who owns what, structurally. Hiding the derived files behind
// a leading dot was the alternative and is worse on both counts: it does not
// stop anyone editing them, and it hides them from whoever later needs to
// clear one out.
//
// The two kinds also differ in what damage a hand edit does. projects.json is
// regenerated by the next rescan, so meddling costs nothing but confusion.
// environments.json is the only record of which process belongs to which
// project — delete an entry and a running claude becomes an orphan this tool
// can neither find nor stop.
const stateSubdir = "state"

// stateSchemaVersion is the format version of the files under state/.
//
// It exists now rather than when it is first needed, because the window for
// introducing it closes at the first release. Whatever 1.0.0 writes becomes a
// format that has to be migrated from forever, and a migration that must guess
// which build wrote a file is a migration that breaks. Adding the marker costs
// a line per file today; adding it after release costs a guess.
//
// Bump it only when a change cannot be absorbed by reading the old fields.
// Adding an optional field does not qualify.
const stateSchemaVersion = 1

// checkSchemaVersion decides whether a state file can be read, and says what
// to do when it cannot.
//
// The two directions fail differently and deserve different advice. A file
// from a newer build means this binary is behind. A file from an older format
// means the data has to be regenerated or discarded, and only the caller knows
// which of those is cheap — hence remedy.
func checkSchemaVersion(path string, found int, remedy string) error {
	switch {
	case found == stateSchemaVersion:
		return nil
	case found > stateSchemaVersion:
		return fmt.Errorf("%s is in format %d, but this build of %s reads format %d — update %s",
			path, found, appName, stateSchemaVersion, appName)
	default:
		return fmt.Errorf("%s is in format %d, which this build of %s no longer reads — %s",
			path, found, appName, remedy)
	}
}

func configFile(home string) string      { return filepath.Join(home, "config.json") }
func stateFile(home, name string) string { return filepath.Join(home, stateSubdir, name) }
func logsDir(home string) string         { return filepath.Join(home, stateSubdir, "logs") }

// ensureLayout creates the directories, so that a first run and a permission
// problem are distinguishable before anything tries to write.
func ensureLayout(home string) error {
	if err := os.MkdirAll(filepath.Join(home, stateSubdir), 0o700); err != nil {
		return fmt.Errorf("create state directory %s: %w", home, err)
	}
	return nil
}

// writeFileAtomic writes data to path via a temporary file in the same
// directory followed by a rename, so a reader never observes a half-written
// file and a crash mid-write cannot destroy the previous contents.
//
// The parent directory is created if missing, which removes an ordering
// dependency between whoever sets up the layout and whoever writes first.
func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, perm); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		// Leaving the temporary file behind would make the next write fail in
		// confusing ways, so clean up before reporting.
		os.Remove(tmp)
		return err
	}
	return nil
}
